/**
 * ingredientRecipe.service — product recipes + auto-generated modifier groups (Session 1).
 *
 * NOTE: named ingredientRecipe (not recipe) because a legacy recipe.service.ts
 * already exists for the recipes/recipe_lines system. This is the NEW, additive
 * ingredient-aware recipe layer (product_ingredients), kept fully separate.
 *
 * When a recipe-mode product's recipe changes, this regenerates two auto groups:
 *   - "Omissions": "No X" for each optional ingredient (deducts nothing)
 *   - "Extras":    "Extra X" for each optional ingredient (deducts extra qty)
 * Universal add-ons are fetched dynamically at POS time (not stored on product).
 *
 * recipe_mode = false leaves the existing modifier system completely untouched.
 * Org-scoped throughout. Resilient to a pending migration 028.
 */

import { query, withTransaction } from '../db/client';
import { NotFoundError } from '../errors';
import { ingredientSystemReady, listUniversalAddons } from './ingredient.service';

// ── Types ─────────────────────────────────────────────────────────────────────────

export interface RecipeIngredientInput {
  ingredientId: string;
  quantity: number;
  unit: string;
  isOptional: boolean;
  omissionPriceDelta: number;
  extraPriceDelta: number;
  extraQuantity: number;
  displayOrder: number;
}

export interface RecipeIngredientRow {
  id: string;
  product_id: string;
  ingredient_id: string;
  organization_id: string;
  quantity: number;
  unit: string;
  is_optional: boolean;
  omission_price_delta: number;
  extra_price_delta: number;
  extra_quantity: number;
  display_order: number;
  ingredient_name: string;
  ingredient_unit: string;
}

export interface POSModifierOption {
  id: string;
  name: string;
  priceDelta: number;
  isDefault: boolean;
  sortOrder: number;
  modifierType?: string;
  ingredientId?: string | null;
  ingredientQty?: number | null;
}

export interface POSModifierGroup {
  id: string;
  name: string;
  selectionType: string;
  minSelections: number;
  maxSelections: number | null;
  sortOrder: number;
  groupType: string;
  isAutoGenerated: boolean;
  modifiers: POSModifierOption[];
}

// ── Helpers ────────────────────────────────────────────────────────────────────

async function assertProduct(orgId: string, productId: string): Promise<void> {
  const { rows: [p] } = await query(
    `SELECT id FROM products WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`,
    [productId, orgId],
  );
  if (!p) throw new NotFoundError('Product');
}

// ── Get recipe ────────────────────────────────────────────────────────────────

export async function getProductRecipe(orgId: string, productId: string): Promise<RecipeIngredientRow[]> {
  if (!(await ingredientSystemReady())) return [];
  const { rows } = await query<RecipeIngredientRow>(
    `SELECT pi.*, i.name AS ingredient_name, i.unit AS ingredient_unit
       FROM product_ingredients pi
       JOIN ingredients i ON i.id = pi.ingredient_id AND i.deleted_at IS NULL
      WHERE pi.product_id = $1 AND pi.organization_id = $2
      ORDER BY pi.display_order ASC, i.name ASC`,
    [productId, orgId],
  );
  return rows;
}

// ── Replace recipe ──────────────────────────────────────────────────────────────

export async function setProductRecipe(
  orgId: string,
  productId: string,
  ingredients: RecipeIngredientInput[],
): Promise<RecipeIngredientRow[]> {
  await assertProduct(orgId, productId);

  await withTransaction(async (client) => {
    await client.query(
      `DELETE FROM product_ingredients WHERE product_id = $1 AND organization_id = $2`,
      [productId, orgId],
    );
    for (const ing of ingredients) {
      const { rows: [ok] } = await client.query(
        `SELECT id FROM ingredients WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`,
        [ing.ingredientId, orgId],
      );
      if (!ok) continue;
      await client.query(
        `INSERT INTO product_ingredients
           (product_id, ingredient_id, organization_id, quantity, unit,
            is_optional, omission_price_delta, extra_price_delta, extra_quantity, display_order)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
         ON CONFLICT (product_id, ingredient_id) DO UPDATE SET
           quantity = EXCLUDED.quantity, unit = EXCLUDED.unit, is_optional = EXCLUDED.is_optional,
           omission_price_delta = EXCLUDED.omission_price_delta, extra_price_delta = EXCLUDED.extra_price_delta,
           extra_quantity = EXCLUDED.extra_quantity, display_order = EXCLUDED.display_order`,
        [
          productId, ing.ingredientId, orgId, ing.quantity, ing.unit ?? 'qty',
          ing.isOptional ?? true, Math.round(ing.omissionPriceDelta ?? 0), Math.round(ing.extraPriceDelta ?? 0),
          ing.extraQuantity ?? 1, ing.displayOrder ?? 0,
        ],
      );
    }
  });

  const { rows: [p] } = await query<{ recipe_mode: boolean }>(
    `SELECT recipe_mode FROM products WHERE id = $1 AND organization_id = $2`,
    [productId, orgId],
  );
  if (p?.recipe_mode) await regenerateAutoModifiers(orgId, productId);

  return getProductRecipe(orgId, productId);
}

// ── Recipe mode toggle ───────────────────────────────────────────────────────────

export async function enableRecipeMode(orgId: string, productId: string): Promise<{ success: true }> {
  await assertProduct(orgId, productId);
  await query(
    `UPDATE products SET recipe_mode = true, updated_at = now() WHERE id = $1 AND organization_id = $2`,
    [productId, orgId],
  );
  await regenerateAutoModifiers(orgId, productId);
  return { success: true };
}

export async function disableRecipeMode(orgId: string, productId: string): Promise<{ success: true }> {
  await assertProduct(orgId, productId);
  // Preserve auto-generated modifiers in case recipe mode is re-enabled.
  await query(
    `UPDATE products SET recipe_mode = false, updated_at = now() WHERE id = $1 AND organization_id = $2`,
    [productId, orgId],
  );
  return { success: true };
}

// ── Auto-generate omission/extra modifier groups ─────────────────────────────────

export async function regenerateAutoModifiers(orgId: string, productId: string): Promise<void> {
  if (!(await ingredientSystemReady())) return;

  const optional = await query<{
    ingredient_id: string; ingredient_name: string;
    quantity: number; extra_quantity: number;
    omission_price_delta: number; extra_price_delta: number; display_order: number;
  }>(
    `SELECT pi.ingredient_id, i.name AS ingredient_name, pi.quantity, pi.extra_quantity,
            pi.omission_price_delta, pi.extra_price_delta, pi.display_order
       FROM product_ingredients pi
       JOIN ingredients i ON i.id = pi.ingredient_id AND i.deleted_at IS NULL
      WHERE pi.product_id = $1 AND pi.organization_id = $2 AND pi.is_optional = true
      ORDER BY pi.display_order ASC, i.name ASC`,
    [productId, orgId],
  );
  const items = optional.rows;

  await withTransaction(async (client) => {
    // Clean regeneration — deleting the group cascades its modifiers + junction rows.
    await client.query(
      `DELETE FROM modifier_groups
        WHERE organization_id = $1 AND source_product_id = $2 AND is_auto_generated = true`,
      [orgId, productId],
    );

    if (items.length === 0) return; // nothing optional → no auto groups

    const makeGroup = async (name: string, groupType: string, sortOrder: number): Promise<string> => {
      const { rows: [g] } = await client.query<{ id: string }>(
        `INSERT INTO modifier_groups
           (organization_id, name, selection_type, min_selections, max_selections, sort_order,
            is_active, group_type, is_auto_generated, source_product_id)
         VALUES ($1,$2,'multiple',0,NULL,$3,true,$4,true,$5)
         RETURNING id`,
        [orgId, name, sortOrder, groupType, productId],
      );
      await client.query(
        `INSERT INTO product_modifier_groups (product_id, modifier_group_id, sort_order)
         VALUES ($1,$2,$3) ON CONFLICT DO NOTHING`,
        [productId, g.id, sortOrder],
      );
      return g.id;
    };

    // Omissions
    const omissionGroupId = await makeGroup('Omissions', 'omissions', 0);
    let i = 0;
    for (const it of items) {
      await client.query(
        `INSERT INTO modifiers
           (group_id, name, price_delta, sort_order, is_active,
            modifier_type, ingredient_id, ingredient_qty, is_auto_generated)
         VALUES ($1,$2,$3,$4,true,'omission',$5,$6,true)`,
        [omissionGroupId, `No ${it.ingredient_name}`, it.omission_price_delta, i++, it.ingredient_id, -Number(it.quantity)],
      );
    }

    // Extras
    const extrasGroupId = await makeGroup('Extras', 'extras', 1);
    i = 0;
    for (const it of items) {
      await client.query(
        `INSERT INTO modifiers
           (group_id, name, price_delta, sort_order, is_active,
            modifier_type, ingredient_id, ingredient_qty, is_auto_generated)
         VALUES ($1,$2,$3,$4,true,'extra',$5,$6,true)`,
        [extrasGroupId, `Extra ${it.ingredient_name}`, it.extra_price_delta, i++, it.ingredient_id, Number(it.extra_quantity)],
      );
    }
  });
}

// ── POS modifier resolver ────────────────────────────────────────────────────────

async function loadAssignedGroups(orgId: string, productId: string, withRecipeCols: boolean): Promise<POSModifierGroup[]> {
  const recipeCols = withRecipeCols
    ? `mg.group_type, mg.is_auto_generated,`
    : `'custom'::varchar AS group_type, false AS is_auto_generated,`;
  const optCols = withRecipeCols
    ? `'modifierType', mo.modifier_type, 'ingredientId', mo.ingredient_id, 'ingredientQty', mo.ingredient_qty`
    : `'modifierType', 'custom', 'ingredientId', NULL, 'ingredientQty', NULL`;

  const { rows } = await query<{
    id: string; name: string; selection_type: string;
    min_selections: number; max_selections: number | null; sort_order: number;
    group_type: string; is_auto_generated: boolean;
    modifiers: POSModifierOption[] | null;
  }>(
    `SELECT mg.id, mg.name, mg.selection_type, mg.min_selections, mg.max_selections,
            pmg.sort_order, ${recipeCols}
            COALESCE(JSON_AGG(JSON_BUILD_OBJECT(
              'id', mo.id, 'name', mo.name, 'priceDelta', mo.price_delta,
              'isDefault', mo.is_default, 'sortOrder', mo.sort_order, ${optCols}
            ) ORDER BY mo.sort_order ASC) FILTER (WHERE mo.id IS NOT NULL), '[]'::json) AS modifiers
       FROM product_modifier_groups pmg
       JOIN modifier_groups mg ON mg.id = pmg.modifier_group_id
         AND mg.deleted_at IS NULL AND mg.is_active = true AND mg.organization_id = $2
       LEFT JOIN modifiers mo ON mo.group_id = mg.id AND mo.deleted_at IS NULL AND mo.is_active = true
      WHERE pmg.product_id = $1
      GROUP BY mg.id, mg.name, mg.selection_type, mg.min_selections, mg.max_selections, pmg.sort_order
               ${withRecipeCols ? ', mg.group_type, mg.is_auto_generated' : ''}
      ORDER BY pmg.sort_order ASC`,
    [productId, orgId],
  );

  return rows.map((g) => ({
    id: g.id, name: g.name, selectionType: g.selection_type,
    minSelections: g.min_selections, maxSelections: g.max_selections, sortOrder: g.sort_order,
    groupType: g.group_type, isAutoGenerated: g.is_auto_generated,
    modifiers: g.modifiers ?? [],
  }));
}

async function buildUniversalGroup(orgId: string, productId: string): Promise<POSModifierGroup | null> {
  const addons = await listUniversalAddons(orgId);
  if (!addons.length) return null;

  const { rows: excluded } = await query<{ ingredient_id: string }>(
    `SELECT ingredient_id FROM product_ingredient_exclusions
      WHERE product_id = $1 AND organization_id = $2`,
    [productId, orgId],
  );
  const excludedSet = new Set(excluded.map((e) => e.ingredient_id));
  const visible = addons.filter((a) => !excludedSet.has(a.id));
  if (!visible.length) return null;

  return {
    id: 'universal',
    name: 'Add-ons',
    selectionType: 'multiple',
    minSelections: 0,
    maxSelections: null,
    sortOrder: 999,
    groupType: 'add_ons',
    isAutoGenerated: true,
    modifiers: visible.map((a, idx) => ({
      id: a.id,
      name: a.universal_addon_label?.trim() || `Add ${a.name}`,
      priceDelta: a.universal_addon_price,
      isDefault: false,
      sortOrder: idx,
      modifierType: 'add_on',
      ingredientId: a.id,
      ingredientQty: 1,
    })),
  };
}

export interface ProductModifiersForPOS {
  recipeMode: boolean;
  groups: POSModifierGroup[];
}

export async function getProductModifiersForPOS(orgId: string, productId: string): Promise<ProductModifiersForPOS> {
  const ready = await ingredientSystemReady();

  let recipeMode = false;
  if (ready) {
    const { rows: [p] } = await query<{ recipe_mode: boolean }>(
      `SELECT recipe_mode FROM products WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`,
      [productId, orgId],
    );
    if (!p) throw new NotFoundError('Product');
    recipeMode = Boolean(p.recipe_mode);
  } else {
    await assertProduct(orgId, productId);
  }

  const groups = await loadAssignedGroups(orgId, productId, ready);

  // recipe_mode FALSE → existing behavior (return assigned groups untouched).
  if (!recipeMode) return { recipeMode: false, groups };

  // recipe_mode TRUE → omissions, extras, custom, then dynamic universal add-ons.
  const omissions = groups.filter((g) => g.groupType === 'omissions');
  const extras = groups.filter((g) => g.groupType === 'extras');
  const custom = groups.filter((g) => !g.isAutoGenerated);
  const ordered = [...omissions, ...extras, ...custom];

  const universal = await buildUniversalGroup(orgId, productId);
  if (universal) ordered.push(universal);

  return { recipeMode: true, groups: ordered };
}

// ── Universal add-on exclusions ──────────────────────────────────────────────────

export async function addIngredientExclusion(orgId: string, productId: string, ingredientId: string): Promise<{ success: true }> {
  await assertProduct(orgId, productId);
  await query(
    `INSERT INTO product_ingredient_exclusions (product_id, ingredient_id, organization_id)
     VALUES ($1,$2,$3) ON CONFLICT DO NOTHING`,
    [productId, ingredientId, orgId],
  );
  return { success: true };
}

export async function removeIngredientExclusion(orgId: string, productId: string, ingredientId: string): Promise<{ success: true }> {
  await query(
    `DELETE FROM product_ingredient_exclusions
      WHERE product_id = $1 AND ingredient_id = $2 AND organization_id = $3`,
    [productId, ingredientId, orgId],
  );
  return { success: true };
}
